### ISSUE TITLE
Error during run build

### ISSUE THREAD

**Issue by giaffa86** [AngularDashboardFramework/AngularDashboardFramework#3]
Hello guys,
I'm trying to run this project, but when I execute `npm run build` I get:
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng-adf@0.1.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ng-adf@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`
I've running successfully npm install before lauch the dashboard.
Can anyone help me?
Thanks in advance.

UPDATE: I noticed that before npm ERR i get:

`Error at  mypath/AngularDashboardFramework/.tmp/services/runtime.service.ts:8:33: Cannot find module 'rxjs/Observable/ErrorObservable'.
Error at mypath/AngularDashboardFramework/.tmp/services/runtime.service.ts:16:12: Return type of public static method from exported class has or is using name 'ErrorObservable' from external module "mypath/AngularDashboardFramework/node_modules/rxjs/observable/ErrorObservable" but cannot be named.
[16:27:49] 'ngc' errored after 3.24 s
[16:27:49] Error: ngc compilation failed
    at ngc.then (mypath/AngularDashboardFramework/gulpfile.js:59:15)
    at <anonymous>
`

**Comment by jayhamilton** [comment]
I have not tried to build this version. My version seems to build fine.

**Comment by giaffa86** [comment]
Which are the differences?

**Comment by jayhamilton** [comment]
The version you tried to build was an updated version of the original code base I currently maintain and update in the following project:
https://github.com/catalogicsoftware/ngx-dynamic-dashboard-framework
The developer of the code you are trying to build made a several good changes to my original code but I just have not had the bandwidth to bring those changes back into my code. Changes include changing the widget names to be more generic, allow the project to be used as a component, made the css implementation more flexible, etc. My current version is still a bit specific to a project I am working on. That said, it should build and can be launched.

**Comment by giaffa86** [comment]
Thank you jay,
I've been trying your demo and it works.

**Comment by jayhamilton** [comment]
@giaffa86 good. At some point I hope to see Michael Rice's changes incorporated into my project.
